### ISSUE TITLE
design question: why the two-step process?

### ISSUE THREAD

**Issue by anarcat** [firstlookmedia/dangerzone#111]
In the Dockerfile, there are two sets of script: one to convert the file to pixels, then that container stops, and another container processes those pixels back into a PDF.

why? what attack vector does that design specifically protect against?

i understand the multistage process (going to pixels and back), I just don't understand the interest of doing it in two separate containers (and believe this would be useful to document publicly).

(incidentally, I also wonder why the container runs as root, but I have taken the liberty of assuming that is a design limitation that can be fixed, in #52 and https://github.com/firstlookmedia/dangerzone-converter/pull/7)

**Comment by micahflee** [comment]
The rationale for using two separate containers is to prevent malware that specifically targets Dangerzone from succeeding.

Here's how it currently works:

- User opens the `.odt` file in dangerzone
- First container
  - Uses headless libreoffice to convert `.odt` to `.pdf`
  - Converts the PDF to pixels
  - Container closes
- Second container
  - Converts pixels to safe PDF
  - Optionally OCRs it
  - Final `-safe.pdf` file is accessible to the host OS
  - Container closes

If it was just one container, it would work like this instead:

- User opens the `.odt` file in dangerzone
- Only container
  - Uses headless libreoffice to convert `.odt` to `.pdf`
  - Converts the PDF to pixels
  - Converts pixels to safe PDF
  - Optionally OCRs it
  - Final `-safe.pdf` file is accessible to the host OS
  - Container closes

Now let's say someone creates a malicious .odt that specifically targets Dangerzone, using a libreoffice exploit:

- User opens `malware.odt` file in dangerzone
- Only container
  - Uses headless libreoffice to convert `.odt` to `.pdf`, but exploits a vulnerability in libreoffice and has code execution
  - Uses this code execute to write a `-safe.pdf` accessible to the host OS, but that's _actually malicious_
  - Container closes

It's possible, in a case like this, to end up with a "safe" PDF that isn't actually safe. The two container setup prevents this by _forcing_ the pixels step.

- User opens the `malware.odt` file in dangerzone
- First container
  - Uses headless libreoffice to convert `.odt` to `.pdf`, but exploits a vulnerability in libreoffice and has code execution
  - Whatever it does with its malware, it _must end up writing nothing but pixel data_, which can only contain colors, not malware
  - Container closes
- Second container
  - Converts pixels (whatever they happen to be) to safe PDF
  - Final `-safe.pdf` file is accessible to the host OS, and we know for sure it's safe because we know it must have come from pixel data, and wasn't actually written by malware with code execution
  - Container closes

**Comment by anarcat** [comment]
On 2021-04-15 11:46:31, Micah Lee wrote:

[...]

> Now let's say someone creates a malicious .odt that specifically targets Dangerzone, using a libreoffice exploit:
>
> - User opens `malware.odt` file in dangerzone
> - Only container
>   - Uses headless libreoffice to convert `.odt` to `.pdf`, but exploits a vulnerability in libreoffice and has code execution
>   - Uses this code execute to write a `-safe.pdf` accessible to the host OS, but that's _actually malicious_
>   - Container closes

I see, so your rationale is that the attacker could skip the pixels
step, essentially. That's interesting, I didn't think of that, and now
it makes sense.

Certainly makes this much harder to run as a web service, because now
you need a two-step process, but at least I know now. :)

a.

-- 
The desire to sacrifice an entire lifetime to the noblest of ideals
serves no purpose if one works alone.
                        - Che Guevara

**Comment by micahflee** [comment]
I think for a web service it would make sense to set up some sort of job queue -- especially if you want it to be able to scale ever. So someone uploads files, it saves them and then creates pending jobs in a queue to process them, and then does the two-step container conversion stuff as soon as it gets to them in the queue. The web app could using ajax pulling or websockets (or just refresh, if no javascript) to keep track of the progress of the conversion jobs and know when they're finished.

**Comment by anarcat** [comment]
that's interesting. so i guess i'd see the point of having another
container for the web app then. i was hoping to keep this simple :p

i wasn't thinking of the "hosting this publicly" idea so much,
actually. i was mostly thinking "private self-hosting" and just changing
the way the GUI app works, so that power users could get away with using
curl to pipe stuff in the backend.

but you're right: if you want to host this publicly, you'll definitely
need a queue of some sort.
