### ISSUE TITLE
error Temporary failure in name resolution

### ISSUE THREAD

**Issue by gy741** [firstlookmedia/dangerzone#83]
Hello,

I have the following error in Amazon EC2.

"Merge failed: None" and "Temporary failure in name resolution "

```
ubuntu@ip-172-31-10-249:~$ sudo dangerzone
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Qt: XKEYBOARD extension not present on the X server.
Temporary directories created, dangerous=/tmp/dangerzone-pixel-39u4q35g, safe=/tmp/dangerzone-safe-bc50y2ex
Executing: /usr/bin/pkexec /usr/bin/dangerzone-container ls
Temporary directories created, dangerous=/tmp/dangerzone-pixel-sv2a3gv8, safe=/tmp/dangerzone-safe-9gcwfyga
Executing: /usr/bin/pkexec /usr/bin/dangerzone-container ls flmcode/dangerzone
Executing: /usr/bin/pkexec /usr/bin/dangerzone-container pull
Executing: /usr/bin/docker pull flmcode/dangerzone

Using default tag: latest
latest: Pulling from flmcode/dangerzone
f15005b0235f: Already exists
5420c1e19986: Already exists
21e7c0555214: Already exists
47c772eb47a3: Already exists
Digest: sha256:f4597aa1d1ec402290895d6a3f05f933ef38f82d471c2e6fc62b9cb419b83600
Status: Downloaded newer image for flmcode/dangerzone:latest
docker.io/flmcode/dangerzone:latest


Executing: /usr/bin/pkexec /usr/bin/dangerzone-container documenttopixels --document-filename /home/ubuntu/Downloads/sample_gce_exam_questions.pdf --pixel-dir /tmp/dangerzone-pixel-sv2a3gv8 --container-name flmcode/dangerzone
Executing: /usr/bin/docker run --network none -v /home/ubuntu/Downloads/sample_gce_exam_questions.pdf:/tmp/input_file -v /tmp/dangerzone-pixel-sv2a3gv8:/dangerzone flmcode/dangerzone document-to-pixels


Separating document into pages
Document has 1 pages

Converting page 1 to pixels
sudo: unable to resolve host 85a05282c34f: Temporary failure in name resolution


Executing: /usr/bin/pkexec /usr/bin/dangerzone-container pixelstopdf --pixel-dir /tmp/dangerzone-pixel-sv2a3gv8 --safe-dir /tmp/dangerzone-safe-9gcwfyga --container-name flmcode/dangerzone --ocr 1 --ocr-lang eng
Executing: /usr/bin/docker run --network none -v /tmp/dangerzone-pixel-sv2a3gv8:/dangerzone -v /tmp/dangerzone-safe-9gcwfyga:/safezone -e OCR=1 -e OCR_LANGUAGE=eng flmcode/dangerzone pixels-to-pdf

Document has 0 pages

Merging 0 pages into a single PDF
Merge failed: None

sudo: unable to resolve host 2180fb677422: Temporary failure in name resolution
pdfunite version 0.71.0
Copyright 2005-2018 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information
```

**Comment by mrbrainstem** [comment]
I'm having a similar issue. Running Ubuntu 20.04
I followed the instructions for installing all the prereqs and ran from source and got the same results
Console output below.

dangerzone
Temporary directories created, dangerous=/tmp/dangerzone-pixel-n63lz7ot, safe=/tmp/dangerzone-safe-74_942sn
Executing: /usr/bin/dangerzone-container ls
Temporary directories created, dangerous=/tmp/dangerzone-pixel-qv_6bmki, safe=/tmp/dangerzone-safe-1ztdlpcj
Executing: /usr/bin/dangerzone-container ls flmcode/dangerzone
Executing: /usr/bin/dangerzone-container pull
Executing: /usr/bin/docker pull flmcode/dangerzone

Using default tag: latest
latest: Pulling from flmcode/dangerzone
Digest: sha256:f4597aa1d1ec402290895d6a3f05f933ef38f82d471c2e6fc62b9cb419b83600
Status: Image is up to date for flmcode/dangerzone:latest
docker.io/flmcode/dangerzone:latest


Executing: /usr/bin/dangerzone-container documenttopixels --document-filename /home/betsyr/Downloads/safepdf.pdf --pixel-dir /tmp/dangerzone-pixel-qv_6bmki --container-name flmcode/dangerzone
Executing: /usr/bin/docker run --network none -v /home/betsyr/Downloads/safepdf.pdf:/tmp/input_file -v /tmp/dangerzone-pixel-qv_6bmki:/dangerzone flmcode/dangerzone document-to-pixels


Separating document into pages
Document has 1 pages

Converting page 1 to pixels
sudo: unable to resolve host 82feaacc171e: Temporary failure in name resolution


Executing: /usr/bin/dangerzone-container pixelstopdf --pixel-dir /tmp/dangerzone-pixel-qv_6bmki --safe-dir /tmp/dangerzone-safe-1ztdlpcj --container-name flmcode/dangerzone --ocr 0 --ocr-lang eng
Executing: /usr/bin/docker run --network none -v /tmp/dangerzone-pixel-qv_6bmki:/dangerzone -v /tmp/dangerzone-safe-1ztdlpcj:/safezone -e OCR=0 -e OCR_LANGUAGE=eng flmcode/dangerzone pixels-to-pdf

Document has 0 pages

Merging 0 pages into a single PDF
Merge failed: None

sudo: unable to resolve host d7edbb8a4577: Temporary failure in name resolution
pdfunite version 0.71.0
Copyright 2005-2018 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information

**Comment by micahflee** [comment]
Can you try again with the latest version, 0.1.4?

**Comment by AnonymousPlanet** [comment]
Same issue with 0.1.5 running Ubuntu or XUbuntu.

Tried official Docker and Ubuntu provided Docker packages.

Tried several workarounds without success. Same resolution error on PDF files.

**Comment by StephenGenusa** [comment]
There appears to be confusion in these posts about the failures that are occurring and I'd like to address them to offer some clarity. 

The "Temporary failure in name resolution" errors are unrelated to the other problems reported here _and_ **you should expect to see that error.**

The hostnames being shown, such as 85a05282c34f, are the _temporary_ hostnames of the container instances, and because the container is being executed with the "--network none" parameter, the instance O/S cannot resolve its own hostname. This does not affect functionality of the conversion processes.

The conversion processes, on both Windows and Linux, are using shared temporary directories to pass the files between container and host so networking is not needed. The "--network none" is a security measure to prevent the container from accessing the network.

@gy741  - It is unclear from your post if this is a single failure on a single file or if you are having a reoccurring problem.

@mrbrainstem - PDFs are generated by countless libraries that may or may not conform to expected specifications. Is your failure a one-off or all conversion attempts are failing?

Any one-off failure does not provide sufficient data to troubleshoot. I'd try running Dangerzone using the test documents associated with this project as they are known to work and provide a basis to determine if Dangerzone is setup properly and functioning.

@AnonymousPlanet  - You haven't provided enough detail to troubleshoot. Please post additional details about what is happening like console output and what workarounds you have attempted.

**Comment by micahflee** [comment]
Thanks @StephenGenusa. The "Temporary failure in name resolution" warning isn't a problem and we recently updated the container so that doesn't happen anymore. I'll close this issue and anyone can feel free to open a new more specific one if you're still seeing issues.
